// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        (unknown)
// source: api/protobuf/edge/images.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ImageStatus int32

const (
	ImageStatus_SUCCESS  ImageStatus = 0
	ImageStatus_BUILDING ImageStatus = 1
	ImageStatus_ERROR    ImageStatus = 2
)

// Enum value maps for ImageStatus.
var (
	ImageStatus_name = map[int32]string{
		0: "SUCCESS",
		1: "BUILDING",
		2: "ERROR",
	}
	ImageStatus_value = map[string]int32{
		"SUCCESS":  0,
		"BUILDING": 1,
		"ERROR":    2,
	}
)

func (x ImageStatus) Enum() *ImageStatus {
	p := new(ImageStatus)
	*p = x
	return p
}

func (x ImageStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ImageStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_protobuf_edge_images_proto_enumTypes[0].Descriptor()
}

func (ImageStatus) Type() protoreflect.EnumType {
	return &file_api_protobuf_edge_images_proto_enumTypes[0]
}

func (x ImageStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ImageStatus.Descriptor instead.
func (ImageStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_protobuf_edge_images_proto_rawDescGZIP(), []int{0}
}

type Image struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Base   *Base        `protobuf:"bytes,1,opt,name=base,proto3,oneof" json:"base,omitempty"`
	Status *ImageStatus `protobuf:"varint,2,opt,name=status,proto3,enum=proto.ImageStatus,oneof" json:"status,omitempty"`
}

func (x *Image) Reset() {
	*x = Image{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_edge_images_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image) ProtoMessage() {}

func (x *Image) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_edge_images_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Image.ProtoReflect.Descriptor instead.
func (*Image) Descriptor() ([]byte, []int) {
	return file_api_protobuf_edge_images_proto_rawDescGZIP(), []int{0}
}

func (x *Image) GetBase() *Base {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *Image) GetStatus() ImageStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ImageStatus_SUCCESS
}

type ImageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Images []*Image `protobuf:"bytes,1,rep,name=images,proto3" json:"images,omitempty"`
}

func (x *ImageRequest) Reset() {
	*x = ImageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_edge_images_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageRequest) ProtoMessage() {}

func (x *ImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_edge_images_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageRequest.ProtoReflect.Descriptor instead.
func (*ImageRequest) Descriptor() ([]byte, []int) {
	return file_api_protobuf_edge_images_proto_rawDescGZIP(), []int{1}
}

func (x *ImageRequest) GetImages() []*Image {
	if x != nil {
		return x.Images
	}
	return nil
}

var File_api_protobuf_edge_images_proto protoreflect.FileDescriptor

var file_api_protobuf_edge_images_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65,
	0x64, 0x67, 0x65, 0x2f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1e, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x64, 0x67, 0x65, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x72, 0x0a, 0x05, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x24, 0x0a,
	0x04, 0x62, 0x61, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x48, 0x00, 0x52, 0x04, 0x62, 0x61, 0x73, 0x65,
	0x88, 0x01, 0x01, 0x12, 0x2f, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x6d, 0x61, 0x67,
	0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x48, 0x01, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x88, 0x01, 0x01, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x62, 0x61, 0x73, 0x65, 0x42, 0x09, 0x0a,
	0x07, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x34, 0x0a, 0x0c, 0x49, 0x6d, 0x61, 0x67,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x06, 0x69, 0x6d, 0x61, 0x67,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x06, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x2a, 0x33,
	0x0a, 0x0b, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a,
	0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x42, 0x55,
	0x49, 0x4c, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f,
	0x52, 0x10, 0x02, 0x32, 0x55, 0x0a, 0x0d, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x44, 0x0a, 0x15, 0x41, 0x64, 0x64, 0x49, 0x6d, 0x61, 0x67, 0x65,
	0x54, 0x6f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x51, 0x75, 0x65, 0x75, 0x65, 0x12, 0x13, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x41, 0x76, 0x69, 0x65, 0x6c, 0x79, 0x6f,
	0x31, 0x30, 0x2f, 0x65, 0x64, 0x67, 0x65, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_api_protobuf_edge_images_proto_rawDescOnce sync.Once
	file_api_protobuf_edge_images_proto_rawDescData = file_api_protobuf_edge_images_proto_rawDesc
)

func file_api_protobuf_edge_images_proto_rawDescGZIP() []byte {
	file_api_protobuf_edge_images_proto_rawDescOnce.Do(func() {
		file_api_protobuf_edge_images_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_protobuf_edge_images_proto_rawDescData)
	})
	return file_api_protobuf_edge_images_proto_rawDescData
}

var file_api_protobuf_edge_images_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_protobuf_edge_images_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_protobuf_edge_images_proto_goTypes = []interface{}{
	(ImageStatus)(0),      // 0: proto.ImageStatus
	(*Image)(nil),         // 1: proto.Image
	(*ImageRequest)(nil),  // 2: proto.ImageRequest
	(*Base)(nil),          // 3: proto.Base
	(*emptypb.Empty)(nil), // 4: google.protobuf.Empty
}
var file_api_protobuf_edge_images_proto_depIdxs = []int32{
	3, // 0: proto.Image.base:type_name -> proto.Base
	0, // 1: proto.Image.status:type_name -> proto.ImageStatus
	1, // 2: proto.ImageRequest.images:type_name -> proto.Image
	2, // 3: proto.ImagesService.AddImageToUpdateQueue:input_type -> proto.ImageRequest
	4, // 4: proto.ImagesService.AddImageToUpdateQueue:output_type -> google.protobuf.Empty
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_protobuf_edge_images_proto_init() }
func file_api_protobuf_edge_images_proto_init() {
	if File_api_protobuf_edge_images_proto != nil {
		return
	}
	file_api_protobuf_edge_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_api_protobuf_edge_images_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Image); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protobuf_edge_images_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_protobuf_edge_images_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_protobuf_edge_images_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_protobuf_edge_images_proto_goTypes,
		DependencyIndexes: file_api_protobuf_edge_images_proto_depIdxs,
		EnumInfos:         file_api_protobuf_edge_images_proto_enumTypes,
		MessageInfos:      file_api_protobuf_edge_images_proto_msgTypes,
	}.Build()
	File_api_protobuf_edge_images_proto = out.File
	file_api_protobuf_edge_images_proto_rawDesc = nil
	file_api_protobuf_edge_images_proto_goTypes = nil
	file_api_protobuf_edge_images_proto_depIdxs = nil
}
